### ISSUE TITLE
Confusing about the Locator::convertTargetFLUtoENU()

### ISSUE THREAD

**Issue by weiweikong** [AutoModality/vis_pose_test#7]
Why we need this functions? 
It seems that we transfer the FLU coordinate (target as origin) to ENU coordinate (target as origin), as shown in following figure. Then, we publish the ENU coordinate to `vision_pose/pose` topic, in order to update the current UAV local position. Is that right? 
![image](https://cloud.githubusercontent.com/assets/2463397/12553748/187e03f2-c3b4-11e5-8b6c-760c3bad2eda.png)

**Comment by edkoch** [comment]
Obviously in typical vision systems the frame of reference is with respect to the camera so if the camera is mounted on the vehicle then the origin is the camera (vehicle) which you then need to translate to ENU with the target at the origin. One way to do this is to first translate the target coordinates from the vehicle body frame to the world ENU frame with the vehicle at the origin and then move origin from the vehicle to the target.
